# Generated by Django 3.1 on 2020-08-20 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('jobs', models.CharField(choices=[('rapper', 'rapper'), ('producer', 'producer'), ('art-designer', 'art-designer')], default='general', max_length=100)),
                ('works', models.CharField(choices=[('song', 'song'), ('video', 'video'), ('art-image', 'art-image')], default='general', max_length=100)),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_url', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pinterest_url', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
