# Generated by Django 3.1 on 2020-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200820_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='works',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('image', 'image')], default='general', max_length=100),
        ),
    ]
