# Generated by Django 3.1 on 2020-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200904_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='general', max_length=100),
        ),
    ]
