# Generated by Django 3.1 on 2020-09-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200904_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='works',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jobs',
        ),
        migrations.AddField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(to='users.Jobs'),
        ),
    ]
