# Generated by Django 3.1 on 2020-09-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200904_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='works',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('image', 'image')], default='general', max_length=100),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jobs',
        ),
        migrations.AddField(
            model_name='profile',
            name='jobs',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='general', max_length=100),
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
