# Generated by Django 3.1 on 2020-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200904_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.CharField(choices=[('producer', 'producer'), ('singer', 'singer'), ('rapper', 'rapper'), ('cover arts', 'cover arts'), ('samples', 'samples'), ('sound design', 'sound design'), ('animations', 'animations')], default='general', max_length=100),
        ),
    ]
