# Generated by Django 3.0.7 on 2020-09-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200904_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='works',
        ),
    ]
