# Generated by Django 3.1 on 2020-08-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='general', max_length=100),
        ),
    ]
