# Generated by Django 3.1 on 2020-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200821_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram_url',
            field=models.CharField(default='url', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.CharField(default='url', max_length=100),
            preserve_default=False,
        ),
    ]
