# Generated by Django 3.0.7 on 2020-09-07 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='instagram_url',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='post',
            name='youtube_url',
        ),
    ]
