# Generated by Django 3.0.7 on 2020-09-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200911_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Заголовок',
        ),
    ]
