# Generated by Django 3.0.7 on 2020-09-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200911_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='Урок',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Фото1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='Фото2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image3',
            new_name='Фото3',
        ),
    ]
