# Generated by Django 3.0.7 on 2020-09-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200911_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Фото1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Фото2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Фото3',
            new_name='image3',
        ),
    ]
